# Generated by Django 2.2.1 on 2019-05-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computer_status', '0001_initial'),
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.Computer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_status.ComputerStatus')),
            ],
        ),
    ]
