# Generated by Django 2.2.1 on 2019-05-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerevents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
